[package]
name = "tundra"
version = "0.1.0"
authors = ["Philip Schleiter <phossc@protonmail.com>", "Simon Rumle Tarnow <simon.r.tarnow@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
